// Generated by tools/extract-map-lighting.mjs using BSPSource. Do not hand-edit.
export const BSP_MAP_LIGHTING = {
  "daylight": {
    "label": "Badlands",
    "map": "cp_badlands",
    "skybox": "sky_badlands_01",
    "sampleOrigin": [
      0,
      0,
      364
    ],
    "captureAngles": [
      0,
      45,
      0
    ],
    "focusDistance": 0,
    "lightingOrigin": [
      0,
      0,
      364
    ],
    "ambientProbe": {
      "source": "LUMP_LEAF_AMBIENT_LIGHTING_HDR",
      "position": [
        0,
        0,
        364
      ],
      "requestedLeaf": 1943,
      "sampleLeaf": 1943,
      "sampleCount": 16,
      "cube": [
        [
          0.09,
          0.083251,
          0.110679
        ],
        [
          0.122473,
          0.104811,
          0.132237
        ],
        [
          0.095073,
          0.089307,
          0.120223
        ],
        [
          0.112653,
          0.0972,
          0.123456
        ],
        [
          0.199444,
          0.211053,
          0.299499
        ],
        [
          0.029922,
          0.014855,
          0.011635
        ]
      ]
    },
    "environment": {
      "classname": "light_environment",
      "origin": [
        -88,
        396,
        880
      ],
      "angles": [
        0,
        210,
        0
      ],
      "pitch": -30,
      "light": [
        251,
        201,
        155,
        250
      ],
      "ambient": [
        153,
        159,
        187,
        170
      ],
      "cone": 45,
      "innerCone": 30,
      "fiftyPercentDistance": 0,
      "zeroPercentDistance": 0
    },
    "localLights": [],
    "fog": {
      "color": [
        113,
        115,
        142
      ],
      "color2": [
        255,
        255,
        255
      ],
      "start": 100,
      "end": 7000
    }
  },
  "overcast": {
    "label": "Sawmill",
    "map": "koth_sawmill",
    "skybox": "sky_alpinestorm_01",
    "sampleOrigin": [
      511.677,
      -4.29442,
      160.25
    ],
    "captureAngles": [
      0,
      225,
      0
    ],
    "focusDistance": 0,
    "lightingOrigin": [
      511.677,
      -4.29442,
      160.25
    ],
    "ambientProbe": {
      "source": "LUMP_LEAF_AMBIENT_LIGHTING_HDR",
      "position": [
        511.677,
        -4.29442,
        160.25
      ],
      "requestedLeaf": 1238,
      "sampleLeaf": 1238,
      "sampleCount": 16,
      "cube": [
        [
          0.039083,
          0.024942,
          0.015598
        ],
        [
          0.045781,
          0.030897,
          0.021122
        ],
        [
          0.050904,
          0.034922,
          0.024164
        ],
        [
          0.035873,
          0.022708,
          0.01481
        ],
        [
          0.01394,
          0.008858,
          0.006231
        ],
        [
          0.077436,
          0.050886,
          0.032649
        ]
      ]
    },
    "environment": {
      "classname": "light_environment",
      "origin": [
        112,
        -32,
        872
      ],
      "angles": [
        0,
        300,
        0
      ],
      "pitch": -65,
      "light": [
        170,
        188,
        193,
        600
      ],
      "ambient": [
        92,
        107,
        114,
        500
      ],
      "cone": 45,
      "innerCone": 30,
      "fiftyPercentDistance": 0,
      "zeroPercentDistance": 0
    },
    "localLights": [],
    "fog": {
      "color": [
        143,
        151,
        152
      ],
      "color2": [
        53,
        60,
        56
      ],
      "start": 0,
      "end": 6200
    }
  },
  "indoors": {
    "label": "2Fort",
    "map": "ctf_2fort",
    "skybox": "sky_tf2_04",
    "sampleOrigin": [
      -592,
      3328,
      -65.111
    ],
    "captureAngles": [
      0,
      338,
      0
    ],
    "focusDistance": 128,
    "lightingOrigin": [
      -473.3204666154512,
      3280.0503560427633,
      -65.111
    ],
    "ambientProbe": {
      "source": "LUMP_LEAF_AMBIENT_LIGHTING_HDR",
      "position": [
        -473.3204666154512,
        3280.0503560427633,
        -65.111
      ],
      "requestedLeaf": 402,
      "sampleLeaf": 402,
      "sampleCount": 16,
      "cube": [
        [
          0.049876,
          0.034202,
          0.022148
        ],
        [
          0.039832,
          0.028521,
          0.017689
        ],
        [
          0.064949,
          0.046219,
          0.031621
        ],
        [
          0.031914,
          0.021436,
          0.014691
        ],
        [
          0.016729,
          0.011348,
          0.009183
        ],
        [
          0.09785,
          0.070014,
          0.040246
        ]
      ]
    },
    "environment": {
      "classname": "light_environment",
      "origin": [
        -48,
        32,
        592
      ],
      "angles": [
        0,
        145,
        0
      ],
      "pitch": -45,
      "light": [
        216,
        207,
        194,
        700
      ],
      "ambient": [
        200,
        202,
        230,
        60
      ],
      "cone": 45,
      "innerCone": 30,
      "fiftyPercentDistance": 0,
      "zeroPercentDistance": 0
    },
    "localLights": [
      {
        "origin": [
          -508.05499267578125,
          3073.27001953125,
          -23.99329948425293
        ],
        "intensity": [
          23529.4140625,
          23529.4140625,
          23529.4140625
        ],
        "normal": [
          -3.803587134143527e-8,
          0,
          -1
        ],
        "cluster": 176,
        "type": 2,
        "style": 0,
        "stopdot": 0.42261824011802673,
        "stopdot2": 0.1736481487751007,
        "exponent": 1,
        "radius": 0,
        "constantAttenuation": 0,
        "linearAttenuation": 0,
        "quadraticAttenuation": 1,
        "flags": 0,
        "color": [
          0.038888,
          0.038888,
          0.038888
        ],
        "direction": [
          -0.162561,
          -0.967751,
          0.192435
        ],
        "distance": 213.671
      }
    ],
    "fog": {
      "color": [
        130,
        139,
        170
      ],
      "color2": [
        255,
        255,
        255
      ],
      "start": 100,
      "end": 8000
    }
  },
  "night": {
    "label": "Harvest Event",
    "map": "koth_harvest_event",
    "skybox": "sky_harvest_night_01",
    "sampleOrigin": [
      0,
      0,
      104.25
    ],
    "captureAngles": [
      0,
      45,
      0
    ],
    "focusDistance": 0,
    "lightingOrigin": [
      0,
      0,
      104.25
    ],
    "ambientProbe": {
      "source": "LUMP_LEAF_AMBIENT_LIGHTING_HDR",
      "position": [
        0,
        0,
        104.25
      ],
      "requestedLeaf": 771,
      "sampleLeaf": 771,
      "sampleCount": 16,
      "cube": [
        [
          0.037145,
          0.022061,
          0.024467
        ],
        [
          0.033215,
          0.019415,
          0.026178
        ],
        [
          0.037001,
          0.022157,
          0.022674
        ],
        [
          0.040532,
          0.023432,
          0.033599
        ],
        [
          0.036982,
          0.025169,
          0.054448
        ],
        [
          0.036074,
          0.019976,
          0.013199
        ]
      ]
    },
    "environment": {
      "classname": "light_environment",
      "origin": [
        552,
        -72,
        328.154
      ],
      "angles": [
        0,
        285,
        0
      ],
      "pitch": -20,
      "light": [
        133,
        101,
        158,
        275
      ],
      "ambient": [
        114,
        100,
        151,
        75
      ],
      "cone": 45,
      "innerCone": 30,
      "fiftyPercentDistance": 0,
      "zeroPercentDistance": 0
    },
    "localLights": [],
    "fog": {
      "color": [
        96,
        66,
        94
      ],
      "color2": [
        255,
        255,
        255
      ],
      "start": 100,
      "end": 15000
    }
  }
} as const;
