// Generated by tools/extract-map-lighting.mjs using BSPSource. Do not hand-edit.
export const BSP_MAP_LIGHTING = {
  "daylight": {
    "label": "Badlands daylight",
    "map": "cp_badlands",
    "skybox": "sky_badlands_01",
    "sampleOrigin": null,
    "environment": {
      "classname": "light_environment",
      "origin": [
        -88,
        396,
        880
      ],
      "angles": [
        0,
        210,
        0
      ],
      "pitch": -30,
      "light": [
        251,
        201,
        155,
        250
      ],
      "ambient": [
        153,
        159,
        187,
        170
      ],
      "cone": 45,
      "innerCone": 30,
      "fiftyPercentDistance": 0,
      "zeroPercentDistance": 0
    },
    "localLights": [],
    "fog": {
      "color": [
        113,
        115,
        142
      ],
      "color2": [
        255,
        255,
        255
      ],
      "start": 100,
      "end": 7000
    }
  },
  "overcast": {
    "label": "Sawmill storm",
    "map": "koth_sawmill",
    "skybox": "sky_alpinestorm_01",
    "sampleOrigin": null,
    "environment": {
      "classname": "light_environment",
      "origin": [
        112,
        -32,
        872
      ],
      "angles": [
        0,
        300,
        0
      ],
      "pitch": -65,
      "light": [
        170,
        188,
        193,
        600
      ],
      "ambient": [
        92,
        107,
        114,
        500
      ],
      "cone": 45,
      "innerCone": 30,
      "fiftyPercentDistance": 0,
      "zeroPercentDistance": 0
    },
    "localLights": [],
    "fog": {
      "color": [
        143,
        151,
        152
      ],
      "color2": [
        53,
        60,
        56
      ],
      "start": 0,
      "end": 6200
    }
  },
  "indoors": {
    "label": "2Fort intel room",
    "map": "ctf_2fort",
    "skybox": "sky_tf2_04",
    "sampleOrigin": [
      -488.66,
      3348.51,
      -131.026
    ],
    "environment": {
      "classname": "light_environment",
      "origin": [
        -48,
        32,
        592
      ],
      "angles": [
        0,
        145,
        0
      ],
      "pitch": -45,
      "light": [
        216,
        207,
        194,
        700
      ],
      "ambient": [
        200,
        202,
        230,
        60
      ],
      "cone": 45,
      "innerCone": 30,
      "fiftyPercentDistance": 0,
      "zeroPercentDistance": 0
    },
    "localLights": [
      {
        "classname": "light_spot",
        "origin": [
          -489.397,
          3330.97,
          -30.9933
        ],
        "angles": [
          -75,
          90,
          90
        ],
        "pitch": -75,
        "light": [
          255,
          255,
          255,
          600
        ],
        "ambient": null,
        "cone": 50,
        "innerCone": 30,
        "fiftyPercentDistance": 0,
        "zeroPercentDistance": 0,
        "distance": 101.561
      },
      {
        "classname": "light_spot",
        "origin": [
          -508.055,
          3073.27,
          -23.9933
        ],
        "angles": [
          -90,
          0,
          0
        ],
        "pitch": -90,
        "light": [
          255,
          255,
          255,
          600
        ],
        "ambient": null,
        "cone": 80,
        "innerCone": 65,
        "fiftyPercentDistance": 0,
        "zeroPercentDistance": 0,
        "distance": 295.955
      }
    ],
    "fog": {
      "color": [
        130,
        139,
        170
      ],
      "color2": [
        255,
        255,
        255
      ],
      "start": 100,
      "end": 8000
    }
  },
  "night": {
    "label": "Harvest Halloween night",
    "map": "koth_harvest_event",
    "skybox": "sky_harvest_night_01",
    "sampleOrigin": null,
    "environment": {
      "classname": "light_environment",
      "origin": [
        552,
        -72,
        328.154
      ],
      "angles": [
        0,
        285,
        0
      ],
      "pitch": -20,
      "light": [
        133,
        101,
        158,
        275
      ],
      "ambient": [
        114,
        100,
        151,
        75
      ],
      "cone": 45,
      "innerCone": 30,
      "fiftyPercentDistance": 0,
      "zeroPercentDistance": 0
    },
    "localLights": [],
    "fog": {
      "color": [
        96,
        66,
        94
      ],
      "color2": [
        255,
        255,
        255
      ],
      "start": 100,
      "end": 15000
    }
  }
} as const;
