import type { Grade, Manifest, PaintkitEntry, Team } from './types';
import type { RecipeNode } from '../compositor/types';
import { mockManifest, mockRecipe } from '../dev/mock/data';
import { mockTextures } from '../dev/mock/textures';

export interface DataSource {
  readonly kind: 'real' | 'mock';
  readonly manifest: Manifest;
  // Resolve a texture ref (path or mock key or data: URL) to a loadable URL.
  resolveTexture: (ref: string) => string;
  // Load and parse a recipe stage tree; null if none exists for this combo.
  getRecipe(kit: PaintkitEntry, weaponKey: string, team: Team, wearIndex: number): Promise<RecipeNode | null>;
  // Absolute URL of a weapon GLB, or null when the stage should remain empty.
  getModelUrl(weaponKey: string): string | null;
  // Absolute URL for a manifest-relative asset (icons, etc.), or null when unavailable.
  getAssetUrl(rel: string): string | null;
}

const DATA_ROOT = `${import.meta.env.BASE_URL}data`;

function joinData(rel: string): string {
  if (rel.startsWith('data:') || rel.startsWith('http')) return rel;
  return `${DATA_ROOT}/${rel.replace(/^\/+/, '')}`;
}

// One per-kit recipe file: every variant's stage tree, deduplicated, plus a
// lookup from variant key ("<weaponKey>_<team>[_w<n>]") to a `trees` index.
interface RecipeBundle {
  trees: RecipeNode[];
  variants: Record<string, number>;
}

class RealDataSource implements DataSource {
  readonly kind = 'real' as const;
  private bundleCache = new Map<number, Promise<RecipeBundle | null>>();
  readonly manifest: Manifest;
  constructor(manifest: Manifest) {
    this.manifest = manifest;
  }

  resolveTexture = (ref: string) => joinData(ref);

  getModelUrl(weaponKey: string): string | null {
    const w = this.manifest.weapons.find((x) => x.key === weaponKey);
    return w ? joinData(w.model) : null;
  }

  getAssetUrl(rel: string): string | null {
    return joinData(rel);
  }

  private fetchBundle(kitId: number): Promise<RecipeBundle | null> {
    const cached = this.bundleCache.get(kitId);
    if (cached) return cached;

    const p = (async () => {
      try {
        const res = await fetch(`${DATA_ROOT}/recipes/${kitId}.json`);
        if (!res.ok) return null;
        return (await res.json()) as RecipeBundle;
      } catch {
        return null;
      }
    })();
    this.bundleCache.set(kitId, p);
    return p;
  }

  async getRecipe(kit: PaintkitEntry, weaponKey: string, team: Team, wearIndex: number): Promise<RecipeNode | null> {
    const bundle = await this.fetchBundle(kit.id);
    if (!bundle) return null;

    const wearSuffix = kit.perWear ? `_w${wearIndex}` : '';
    let key = `${weaponKey}_${team}${wearSuffix}`;
    // Team fallback: only `red` is emitted when hasTeamTextures is false, and
    // blu falls back to red.
    if (!(key in bundle.variants) && team === 'blu') {
      key = `${weaponKey}_red${wearSuffix}`;
    }
    const idx = bundle.variants[key];
    return idx === undefined ? null : (bundle.trees[idx] ?? null);
  }
}

class MockDataSource implements DataSource {
  readonly kind = 'mock' as const;
  readonly manifest = mockManifest;
  private textures = mockTextures();

  resolveTexture = (ref: string) => {
    if (ref.startsWith('data:')) return ref;
    const url = this.textures[ref];
    if (!url) throw new Error(`mock texture not found: ${ref}`);
    return url;
  };

  getModelUrl(): string | null {
    return null;
  }

  getAssetUrl(): string | null {
    return null;
  }

  async getRecipe(kit: PaintkitEntry, weaponKey: string, team: Team): Promise<RecipeNode | null> {
    const effectiveTeam: Team = kit.hasTeamTextures ? team : 'red';
    return mockRecipe(kit.id, weaponKey, effectiveTeam);
  }
}

// Rarity grade per paintkit name, generated by tools/extract-grades.mjs from the
// local TF2 install (items_game.txt collection grade tiers). Best-effort: a
// missing or unfetchable file simply leaves every kit's grade undefined.
async function loadGrades(): Promise<Record<string, Grade>> {
  try {
    const res = await fetch(`${DATA_ROOT}/grades.json`);
    if (!res.ok) return {};
    return (await res.json()) as Record<string, Grade>;
  } catch {
    return {};
  }
}

function applyGrades(manifest: Manifest, grades: Record<string, Grade>): Manifest {
  if (!Object.keys(grades).length) return manifest;
  return {
    ...manifest,
    paintkits: manifest.paintkits.map((kit) => {
      const grade = grades[kit.name];
      return grade ? { ...kit, grade } : kit;
    }),
  };
}

// The normal app is real-data only. Mock mode remains an explicit developer
// harness for compositor tests and is never selected as a startup fallback.
export async function loadDataSource(): Promise<DataSource> {
  const params = new URLSearchParams(window.location.search);
  const mode = params.get('data') ?? (params.get('mock') === '1' ? 'mock' : null);

  if (mode === 'mock') return new MockDataSource();

  const [res, grades] = await Promise.all([fetch(`${DATA_ROOT}/manifest.json`), loadGrades()]);
  if (!res.ok) throw new Error(`manifest ${res.status}`);
  const manifest = applyGrades((await res.json()) as Manifest, grades);
  if (!manifest.paintkits?.length) throw new Error('empty manifest');
  return new RealDataSource(manifest);
}
